#!/usr/bin/env python3
"""
Convert PNG/JPG image to RGB565 C array for ESP32
Usage: python image_to_rgb565.py <image.png> <array_name> > output.h
"""

from PIL import Image
import sys
import os

def rgb888_to_rgb565(r, g, b):
    """Convert RGB888 to RGB565 format"""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def image_to_array(image_path, array_name):
    """Convert image to RGB565 C array"""
    if not os.path.exists(image_path):
        print(f"Error: File '{image_path}' not found", file=sys.stderr)
        sys.exit(1)
    
    try:
        img = Image.open(image_path).convert('RGB')
    except Exception as e:
        print(f"Error opening image: {e}", file=sys.stderr)
        sys.exit(1)
    
    width, height = img.size
    total_pixels = width * height
    total_bytes = total_pixels * 2
    
    # Header
    print(f"// Auto-generated from {os.path.basename(image_path)}")
    print(f"// Image size: {width}x{height} pixels")
    print(f"// Array size: {total_pixels} uint16_t values = {total_bytes} bytes")
    print(f"// Generated by: image_to_rgb565.py")
    print("#pragma once\n")
    print(f"const uint16_t {array_name}[{total_pixels}] PROGMEM = {{")
    
    pixels = img.load()
    count = 0
    line = "  "
    
    for y in range(height):
        for x in range(width):
            r, g, b = pixels[x, y]
            rgb565 = rgb888_to_rgb565(r, g, b)
            line += f"0x{rgb565:04X},"
            count += 1
            
            # 12 values per line for readability
            if count % 12 == 0:
                print(line)
                line = "  "
                
                # Progress indicator (to stderr, not stdout)
                if count % 1200 == 0:
                    progress = (count / total_pixels) * 100
                    print(f"\rProgress: {progress:.1f}%", end='', file=sys.stderr)
    
    # Print remaining values
    if line.strip() != "":
        print(line.rstrip(','))
    
    print("};")
    print(f"\n#define {array_name.upper()}_WIDTH {width}")
    print(f"#define {array_name.upper()}_HEIGHT {height}")
    
    print(f"\rConversion complete! {total_bytes} bytes", file=sys.stderr)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python image_to_rgb565.py <image.png> <array_name>", file=sys.stderr)
        print("Example: python image_to_rgb565.py bg_spectrum.png bg_spectrum > bg_spectrum.h", file=sys.stderr)
        sys.exit(1)
    
    image_path = sys.argv[1]
    array_name = sys.argv[2]
    
    image_to_array(image_path, array_name)
