#!/usr/bin/env python3
"""
Convert JPG image to C array for ESP32 (for TJpg_Decoder)
Usage: python jpg_to_array.py <image.jpg> <array_name> > output.h
"""

import sys
import os

def jpg_to_array(jpg_path, array_name):
    """Convert JPG file to C byte array"""
    if not os.path.exists(jpg_path):
        print(f"Error: File '{jpg_path}' not found", file=sys.stderr)
        sys.exit(1)
    
    try:
        with open(jpg_path, 'rb') as f:
            data = f.read()
    except Exception as e:
        print(f"Error reading file: {e}", file=sys.stderr)
        sys.exit(1)
    
    file_size = len(data)
    
    # Header
    print(f"// Auto-generated from {os.path.basename(jpg_path)}")
    print(f"// File size: {file_size} bytes")
    print(f"// Generated by: jpg_to_array.py")
    print("#pragma once\n")
    print(f"const uint8_t {array_name}[] PROGMEM = {{")
    
    line = "  "
    for i, byte in enumerate(data):
        line += f"0x{byte:02X},"
        
        # 16 bytes per line for readability
        if (i + 1) % 16 == 0:
            print(line)
            line = "  "
            
            # Progress indicator
            if (i + 1) % 1600 == 0:
                progress = ((i + 1) / file_size) * 100
                print(f"\rProgress: {progress:.1f}%", end='', file=sys.stderr)
    
    # Print remaining bytes
    if line.strip() != "":
        print(line.rstrip(','))
    
    print("};")
    print(f"\n#define {array_name.upper()}_SIZE {file_size}")
    
    print(f"\rConversion complete! {file_size} bytes", file=sys.stderr)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python jpg_to_array.py <image.jpg> <array_name>", file=sys.stderr)
        print("Example: python jpg_to_array.py bg_spectrum.jpg bg_spectrum_jpg > bg_spectrum_jpg.h", file=sys.stderr)
        sys.exit(1)
    
    jpg_path = sys.argv[1]
    array_name = sys.argv[2]
    
    jpg_to_array(jpg_path, array_name)
